import { NextResponse } from 'next/server';

const DUAS = [
  {
    id: '1',
    title: 'Doa Bangun Tidur',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    latin: 'Alhamdu lillahil ladzi ahyana ba\'da ma amatana wa ilaihin nusyur',
    translation: 'Segala puji bagi Allah yang telah menghidupkan kami sesudah kami mati (tidur) dan hanya kepada-Nya kami dikembalikan',
    category: 'Tidur',
  },
  {
    id: '2',
    title: 'Doa Sebelum Tidur',
    arabic: 'بِاسْمِكَ اللَّهُمَّ أَحْيَا وَأَمُوتُ',
    latin: 'Bismika Allahumma ahya wa amutu',
    translation: 'Dengan menyebut nama-Mu ya Allah, aku hidup dan aku mati',
    category: 'Tidur',
  },
  {
    id: '3',
    title: 'Doa Sebelum Makan',
    arabic: 'بِسْمِ اللهِ وَعَلَى بَرَكَةِ اللهِ',
    latin: 'Bismillahi wa \'ala barakatillahi',
    translation: 'Dengan menyebut nama Allah dan atas berkah Allah',
    category: 'Makan',
  },
  {
    id: '4',
    title: 'Doa Sesudah Makan',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مِنَ الْمُسْلِمِينَ',
    latin: 'Alhamdu lillahil ladzi ath\'amana wa saqona wa ja\'alana minal muslimin',
    translation: 'Segala puji bagi Allah yang telah memberi kami makan dan minum serta menjadikan kami termasuk orang-orang yang muslim',
    category: 'Makan',
  },
  {
    id: '5',
    title: 'Doa Masuk Kamar Mandi',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ',
    latin: 'Allahumma inni a\'udzu bika minal khubutsi wal khaba-its',
    translation: 'Ya Allah, sesungguhnya aku berlindung kepada-Mu dari godaan setan laki-laki dan setan perempuan',
    category: 'Kamar Mandi',
  },
  {
    id: '6',
    title: 'Doa Keluar Kamar Mandi',
    arabic: 'غُفْرَانَكَ',
    latin: 'Ghufronaka',
    translation: 'Aku mohon ampunan-Mu',
    category: 'Kamar Mandi',
  },
  {
    id: '7',
    title: 'Doa Keluar Rumah',
    arabic: 'بِسْمِ اللهِ، تَوَكَّلْتُ عَلَى اللهِ، لاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللهِ',
    latin: 'Bismillah, tawakkaltu \'alallah, la hawla wa la quwwata illa billah',
    translation: 'Dengan menyebut nama Allah, aku bertawakal kepada Allah, tiada daya dan kekuatan kecuali dengan pertolongan Allah',
    category: 'Rumah',
  },
  {
    id: '8',
    title: 'Doa Masuk Rumah',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ الْمَوْلِجِ وَخَيْرَ الْمَخْرَجِ، بِسْمِ اللهِ وَلَجْنَا، وَبِسْمِ اللهِ خَرَجْنَا، وَعَلَى اللهِ رَبِّنَا تَوَكَّلْنَا',
    latin: 'Allahumma inni as-aluka khoirol mauliji wa khoirol makhroji, bismillahi wa lajnaa wa bismillahi khorojnaa wa \'alallahi robbina tawakkalnaa',
    translation: 'Ya Allah, sesungguhnya aku mohon kepada-Mu baiknya tempat masuk dan baiknya tempat keluar dengan menyebut nama Allah kami masuk, dan dengan menyebut nama Allah kami keluar, dan kepada Allah Tuhan kami, kami bertawakkal',
    category: 'Rumah',
  },
  {
    id: '9',
    title: 'Doa Naik Kendaraan',
    arabic: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ، وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ',
    latin: 'Subhanalladzi sakhkhoro lana hadza wa ma kunna lahu muqrinin. Wa inna ila robbina lamunqolibun',
    translation: 'Maha Suci Allah yang telah menundukkan semua ini bagi kami padahal kami sebelumnya tidak mampu menguasainya, dan sesungguhnya kami akan kembali kepada Tuhan kami',
    category: 'Kendaraan',
  },
  {
    id: '10',
    title: 'Doa Sebelum Belajar',
    arabic: 'رَبِّ زِدْنِي عِلْمًا وَارْزُقْنِي فَهْمًا',
    latin: 'Robbi zidni \'ilman warzuqni fahman',
    translation: 'Ya Allah, tambahkanlah kepadaku ilmu dan berikanlah aku pengertian yang baik',
    category: 'Belajar',
  },
  {
    id: '11',
    title: 'Doa Sesudah Belajar',
    arabic: 'اللَّهُمَّ إِنِّي أَسْتَوْدِعُكَ مَا قَرَأْتُ وَمَا حَفِظْتُ وَمَا تَعَلَّمْتُ فَرُدَّهُ عِنْدَ حَاجَتِي إِلَيْهِ إِنَّكَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    latin: 'Allahumma inni astaudi\'uka ma qoro\'tu wa ma hafiztu wa ma ta\'allamtu faruddahu \'inda hajati ilaihi innaka \'ala kulli syai-in qodir',
    translation: 'Ya Allah, sesungguhnya aku menitipkan kepada Engkau ilmu yang telah aku baca, yang telah aku hafalkan dan yang telah aku pelajari, maka kembalikanlah kepadaku ketika aku membutuhkannya. Sesungguhnya Engkau Maha Kuasa atas segala sesuatu',
    category: 'Belajar',
  },
  {
    id: '12',
    title: 'Doa Ketika Turun Hujan',
    arabic: 'اللَّهُمَّ صَيِّبًا نَافِعًا',
    latin: 'Allahumma shoyyiban nafi\'a',
    translation: 'Ya Allah, turunkan lah hujan yang bermanfaat',
    category: 'Hujan',
  },
  {
    id: '13',
    title: 'Doa Setelah Hujan',
    arabic: 'مُطِرْنَا بِفَضْلِ اللهِ وَرَحْمَتِهِ',
    latin: 'Muthirna bifadhlillahi wa rahmatihi',
    translation: 'Kita mendapat hujan berkat karunia Allah dan rahmat-Nya',
    category: 'Hujan',
  },
  {
    id: '14',
    title: 'Doa Ketika Sakit',
    arabic: 'اللَّهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَأْسَ، اشْفِ أَنْتَ الشَّافِي، لاَ شِفَاءَ إِلاَّ شِفَاؤُكَ، شِفَاءً لاَ يُغَادِرُ سَقَمًا',
    latin: 'Allahumma robban nasi adz-hibil ba\'sa isyfi antasy syafi la syifa-a illa syifa-uka syifa-an la yughodiru saqoman',
    translation: 'Ya Allah Tuhan pemilik manusia, hilangkanlah penyakit ini, sembuhkanlah, Engkaulah Yang Maha Menyembuhkan, tidak ada kesembuhan kecuali kesembuhan dari-Mu, kesembuhan yang tidak menyisakan sakit sedikitpun',
    category: 'Kesehatan',
  },
  {
    id: '15',
    title: 'Doa Menjenguk Orang Sakit',
    arabic: 'لاَ بَأْسَ طَهُورٌ إِنْ شَاءَ اللهُ',
    latin: 'La ba\'sa thohuuron insya Allah',
    translation: 'Tidak mengapa, semoga menjadi penghapus dosa, insya Allah',
    category: 'Kesehatan',
  },
  {
    id: '16',
    title: 'Doa Ketika Bercermin',
    arabic: 'اَللَّهُمَّ كَمَا حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي',
    latin: 'Allahumma kama hassanta kholqi fahassin khuluqi',
    translation: 'Ya Allah, sebagaimana Engkau telah baguskan rupa tubuhku, maka baguskanlah akhlakku',
    category: 'Harian',
  },
  {
    id: '17',
    title: 'Doa Bersin',
    arabic: 'اَلْحَمْدُ ِللهِ',
    latin: 'Alhamdulillah',
    translation: 'Segala puji bagi Allah',
    category: 'Harian',
  },
  {
    id: '18',
    title: 'Jawaban Orang yang Bersin',
    arabic: 'يَرْحَمُكَ اللهُ',
    latin: 'Yarhamukallah',
    translation: 'Semoga Allah merahmatimu',
    category: 'Harian',
  },
  {
    id: '19',
    title: 'Doa Memakai Pakaian',
    arabic: 'اَلْحَمْدُ لِلّهِ الَّذِيْ كَسَانِيْ هَذَا وَرَزَقَنِيْهِ مِنْ غَيْرِ حَوْلٍ مِنِّيْ وَلاَقُوَّةٍ',
    latin: 'Alhamdu lillahil ladzi kasani hadza wa rozaqonihi min ghoiri hawlin minni wala quwwatin',
    translation: 'Segala puji bagi Allah yang memberi pakaian ini kepadaku dan memberi rezeki dengan tanpa daya dan kekuatan dariku',
    category: 'Harian',
  },
  {
    id: '20',
    title: 'Doa Melepas Pakaian',
    arabic: 'بِسْمِ اللهِ الَّذِيْ لاَ إِلَهَ إِلاَّ هُوَ',
    latin: 'Bismillahil ladzi la ilaha illa huwa',
    translation: 'Dengan nama Allah yang tiada Tuhan selain Dia',
    category: 'Harian',
  },
  {
    id: '21',
    title: 'Doa Malam Lailatul Qadar',
    arabic: 'اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي',
    latin: 'Allahumma innaka \'afuwwun tuhibbul \'afwa fa\'fu \'anni',
    translation: 'Ya Allah, sesungguhnya Engkau Maha Pemaaf, Engkau menyukai pemaafan, maka maafkanlah aku',
    category: 'Ramadhan',
  },
  {
    id: '22',
    title: 'Doa Berbuka Puasa',
    arabic: 'اللَّهُمَّ لَكَ صُمْتُ وَعَلَى رِزْقِكَ أَفْطَرْتُ',
    latin: 'Allahumma laka sumtu wa \'ala rizqika afthortu',
    translation: 'Ya Allah, untuk-Mu aku berpuasa dan dengan rezeki-Mu aku berbuka',
    category: 'Ramadhan',
  },
  {
    id: '23',
    title: 'Doa Niat Puasa Ramadhan',
    arabic: 'نَوَيْتُ صَوْمَ غَدٍ عَنْ أَدَاءِ فَرْضِ شَهْرِ رَمَضَانَ هَذِهِ السَّنَةِ لِلهِ تَعَالَى',
    latin: 'Nawaitu shauma ghodin \'an adai fardhi syahri romadlona hadzihis sanati lillahi ta\'ala',
    translation: 'Aku niat berpuasa besok untuk menunaikan kewajiban di bulan Ramadhan tahun ini karena Allah Ta\'ala',
    category: 'Ramadhan',
  },
  {
    id: '24',
    title: 'Doa Mohon Kebaikan',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنَ الْخَيْرِ كُلِّهِ عَاجِلِهِ وَآجِلِهِ',
    latin: 'Allahumma inni as-aluka minal khoiri kullihi \'ajilihi wa ajilihi',
    translation: 'Ya Allah, sesungguhnya aku memohon kepada-Mu segala kebaikan, baik yang segera maupun yang lambat',
    category: 'Harian',
  },
  {
    id: '25',
    title: 'Doa Mohon Perlindungan',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْكَسَلِ',
    latin: 'Allahumma inni a\'udzu bika minal hammi wal hazani wal \'ajzi wal kasali',
    translation: 'Ya Allah, sesungguhnya aku berlindung kepada-Mu dari kesedihan, kesusahan, kelemahan, dan kemalasan',
    category: 'Harian',
  },
];

export async function GET() {
  try {
    return NextResponse.json(DUAS);
  } catch (error) {
    console.error('Error fetching duas:', error);
    return NextResponse.json(
      { error: 'Failed to fetch duas' },
      { status: 500 }
    );
  }
}
